wandb_version: 1

_disable_action_flattening:
  desc: null
  value: false
_disable_execution_plan_api:
  desc: null
  value: true
_disable_preprocessor_api:
  desc: null
  value: false
_fake_gpus:
  desc: null
  value: false
_tf_policy_handles_more_than_one_loss:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1667733028.316395
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 4
      - 5
action_space:
  desc: null
  value: null
actions_in_input_normalized:
  desc: null
  value: false
always_attach_evaluation_results:
  desc: null
  value: false
batch_mode:
  desc: null
  value: truncate_episodes
buffer_size:
  desc: null
  value: -1
callbacks:
  desc: null
  value: ray.rllib.algorithms.callbacks.DefaultCallbacks
clip_actions:
  desc: null
  value: false
clip_param:
  desc: null
  value: 0.3
clip_rewards:
  desc: null
  value: null
collect_metrics_timeout:
  desc: null
  value: -1
compress_observations:
  desc: null
  value: false
create_env_on_driver:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
custom_resources_per_worker:
  desc: null
  value: {}
disable_env_checking:
  desc: null
  value: false
eager_max_retraces:
  desc: null
  value: 20
eager_tracing:
  desc: null
  value: false
enable_async_evaluation:
  desc: null
  value: false
enable_connectors:
  desc: null
  value: false
enable_tf1_exec_eagerly:
  desc: null
  value: false
entropy_coeff:
  desc: null
  value: 0.0
entropy_coeff_schedule:
  desc: null
  value: null
env:
  desc: null
  value: null
env_config:
  desc: null
  value: {}
env_task_fn:
  desc: null
  value: null
evaluation_config:
  desc: null
  value: {}
evaluation_duration:
  desc: null
  value: 3
evaluation_duration_unit:
  desc: null
  value: episodes
evaluation_interval:
  desc: null
  value: 1
evaluation_num_episodes:
  desc: null
  value: -1
evaluation_num_workers:
  desc: null
  value: 1
evaluation_parallel_to_training:
  desc: null
  value: false
evaluation_sample_timeout_s:
  desc: null
  value: 180.0
exploration_config:
  desc: null
  value:
    type: StochasticSampling
explore:
  desc: null
  value: true
extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
fake_sampler:
  desc: null
  value: false
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 0.99
grad_clip:
  desc: null
  value: null
horizon:
  desc: null
  value: null
ignore_worker_failures:
  desc: null
  value: false
in_evaluation:
  desc: null
  value: false
input:
  desc: null
  value: sampler
input_config:
  desc: null
  value: {}
input_evaluation:
  desc: null
  value: -1
keep_per_episode_custom_metrics:
  desc: null
  value: false
kl_coeff:
  desc: null
  value: 0.2
kl_target:
  desc: null
  value: 0.01
lambda:
  desc: null
  value: 1.0
learning_starts:
  desc: null
  value: -1
local_tf_session_args:
  desc: null
  value:
    inter_op_parallelism_threads: 8
    intra_op_parallelism_threads: 8
log_level:
  desc: null
  value: WARN
log_sys_usage:
  desc: null
  value: true
logger_config:
  desc: null
  value: null
logger_creator:
  desc: null
  value: null
lr:
  desc: null
  value: 5.0e-05
lr_schedule:
  desc: null
  value: null
metrics_episode_collection_timeout_s:
  desc: null
  value: 60.0
metrics_num_episodes_for_smoothing:
  desc: null
  value: 100
metrics_smoothing_episodes:
  desc: null
  value: -1
min_iter_time_s:
  desc: null
  value: -1
min_sample_timesteps_per_iteration:
  desc: null
  value: 0
min_sample_timesteps_per_reporting:
  desc: null
  value: -1
min_time_s_per_iteration:
  desc: null
  value: null
min_time_s_per_reporting:
  desc: null
  value: -1
min_train_timesteps_per_iteration:
  desc: null
  value: 0
min_train_timesteps_per_reporting:
  desc: null
  value: -1
model:
  desc: null
  value:
    _disable_action_flattening: false
    _disable_preprocessor_api: false
    _time_major: false
    _use_default_native_models: false
    attention_dim: 64
    attention_head_dim: 32
    attention_init_gru_gate_bias: 2.0
    attention_memory_inference: 50
    attention_memory_training: 50
    attention_num_heads: 1
    attention_num_transformer_units: 1
    attention_position_wise_mlp_dim: 32
    attention_use_n_prev_actions: 0
    attention_use_n_prev_rewards: 0
    conv_activation: relu
    conv_filters: null
    custom_action_dist: null
    custom_model: null
    custom_model_config: {}
    custom_preprocessor: null
    dim: 84
    fcnet_activation: tanh
    fcnet_hiddens:
    - 256
    - 256
    framestack: true
    free_log_std: false
    grayscale: false
    lstm_cell_size: 256
    lstm_use_prev_action: false
    lstm_use_prev_action_reward: -1
    lstm_use_prev_reward: false
    max_seq_len: 20
    no_final_linear: false
    post_fcnet_activation: relu
    post_fcnet_hiddens: []
    use_attention: false
    use_lstm: false
    vf_share_layers: false
    zero_mean: true
monitor:
  desc: null
  value: -1
multiagent:
  desc: null
  value:
    count_steps_by: env_steps
    observation_fn: null
    policies: {}
    policies_to_train: null
    policy_map_cache: null
    policy_map_capacity: 100
    policy_mapping_fn: null
    replay_mode: independent
no_done_at_end:
  desc: null
  value: false
normalize_actions:
  desc: null
  value: true
num_consecutive_worker_failures_tolerance:
  desc: null
  value: 100
num_cpus_for_driver:
  desc: null
  value: 1
num_cpus_per_worker:
  desc: null
  value: 1
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 0
num_gpus_per_worker:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 30
num_workers:
  desc: null
  value: 1
observation_filter:
  desc: null
  value: NoFilter
observation_space:
  desc: null
  value: null
off_policy_estimation_methods:
  desc: null
  value: {}
optimizer:
  desc: null
  value: {}
output:
  desc: null
  value: null
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_config:
  desc: null
  value: {}
output_max_file_size:
  desc: null
  value: 67108864
placement_strategy:
  desc: null
  value: PACK
postprocess_inputs:
  desc: null
  value: false
preprocessor_pref:
  desc: null
  value: deepmind
prioritized_replay:
  desc: null
  value: -1
prioritized_replay_alpha:
  desc: null
  value: -1
prioritized_replay_beta:
  desc: null
  value: -1
prioritized_replay_eps:
  desc: null
  value: -1
recreate_failed_workers:
  desc: null
  value: false
remote_env_batch_wait_ms:
  desc: null
  value: 0
remote_worker_envs:
  desc: null
  value: false
render_env:
  desc: null
  value: false
replay_batch_size:
  desc: null
  value: -1
replay_sequence_length:
  desc: null
  value: null
restart_failed_sub_environments:
  desc: null
  value: false
rollout_fragment_length:
  desc: null
  value: 200
sample_async:
  desc: null
  value: false
sample_collector:
  desc: null
  value: ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector
sampler_perf_stats_ema_coef:
  desc: null
  value: null
seed:
  desc: null
  value: null
sgd_minibatch_size:
  desc: null
  value: 128
shuffle_buffer_size:
  desc: null
  value: 0
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: -1
soft_horizon:
  desc: null
  value: false
sync_filters_on_rollout_workers_timeout_s:
  desc: null
  value: 60.0
synchronize_filters:
  desc: null
  value: true
tf_session_args:
  desc: null
  value:
    allow_soft_placement: true
    device_count:
      CPU: 1
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 2
    log_device_placement: false
timesteps_per_iteration:
  desc: null
  value: -1
train_batch_size:
  desc: null
  value: 4000
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
validate_workers_after_construction:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 10.0
vf_loss_coeff:
  desc: null
  value: 1.0
vf_share_layers:
  desc: null
  value: -1
